### ISSUE TITLE
wrong org ?

### ISSUE THREAD

**Issue by targos** [cheminfo-js/brukerconverter#1]
Shouldn't it live in @cheminfo-js ?
I can move it if that's the case

**Comment by andcastillo** [comment]
it could be. But in that case, jcampconverter is in the wrong place too. It makes almost the same.

**Comment by targos** [comment]
but jcampconverter was here before the existence of the cheminfo-js and it is published in NPM and Bower as belonging to cheminfo. We can eventually do the work required to move them but it is not related to this issue.
The rule is now: a new js project destined to be built with GRM belongs to cheminfo-js

**Comment by lpatiny** [comment]
Moved
